name: black reformat
on: push
jobs:
  linter_name:
    name: runner/black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.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 }}
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: ". --exclude .venv"
      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "Format Python code with psf/black push"
          commit-message: ":art: Format Python code with psf/black"
